---
- name: Provision Cluster Nodes
  hosts: all
  gather_facts: true
  tasks:

    - name: Update /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item]['ansible_facts']['eth1']['ipv4']['address'] }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

    - name: Update System Packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Configure Swappiness
      lineinfile:
        dest: /etc/sysctl.conf
        line: vm.swappiness=1
        state: present

    - name: Check if Reboot is Required
      shell: needs-restarting -r
      register: needs_restarting

    - name: Reboot
      reboot:
      when: needs_restarting.rc == 1

    - name: Install Python Pip
      yum:
        name: python-pip
        state: latest

    - name: Install psycopg2
      pip:
        name: psycopg2==2.7.5
    - name: Remote RPM install with yum
      yum: name=http://mirror.centos.org/centos/7/os/x86_64/Packages/libicu-50.2-4.el7_7.x86_64.rpm
    - name: Get Swappiness
      command: cat /proc/sys/vm/swappiness
      register: swappiness

    - name: Set Swappiness
      command: sysctl vm.swappiness=1
      when: swappiness.stdout|int != 1

- name: Cloudera Manager Installer
  hosts: cloudera0
  gather_facts: false
  tasks:

    - name: Download Cloudera Manager Installer
      get_url:
        url: https://archive.cloudera.com/cm7/7.1.4/cloudera-manager-installer.bin
        dest: /home/vagrant/cloudera-manager-installer.bin
        mode: "0744"
        owner: vagrant
        group: vagrant
...
